#!/bin/bash


_IMAGES=$(mktemp /tmp/dockerimages.XXXXXXXXX)
_container_need_update=false

trap "rm -f ${_IMAGES}" EXIT QUIT INT

docker images -no-trunc 2>&1 |awk '{print $1" "$3}' > ${_IMAGES}
for _dockerid in $(docker ps --quiet); do
    if ! grep -q "$(docker inspect --format "{{ .Config.Image}} {{ .Image}}" ${_dockerid})" ${_IMAGES}; then
    _container_need_update=true
    echo "Container $(docker inspect --format "{{ .Name }}" ${_dockerid})"
  fi
done
${_container_need_update} || echo "All containers are update"
