#!/bin/bash

_registry=$1
_action=$2
_image=$3

WGET='wget -qO- --no-check-certificate'
case  $_action in
  list)
    ${WGET} https://${_registry}:5000/v2/_catalog | python -c 'import sys, json; print(json.load(sys.stdin)["repositories"])' | sed -e "s/\[//;s/]//;s/', /\n/g;s/u'//g;s/'//g"
  ;;
  tag)
    ${WGET} https://${_registry}:5000/v2/${_image}/tags/list
  ;;
  search)
    ${WGET} https://${_registry}:5000/v2/_catalog |grep -ohw "${_image}"
  ;;
  *)
  ;;
esac
